<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20181030 17:06:57.866" generator="Robot 3.0.4 (Python 2.7.15 on win32)">
<suite source="D:\svn\sources\SIWP9006\plc_system_test" id="s1" name="Plc System Test">
<suite source="D:\svn\sources\SIWP9006\plc_system_test\tc.3.3.3.robot" id="s1-s1" name="Tc.3.3.3">
<test id="s1-s1-t1" name="case 3.3.3.1">
<kw type="setup" name="Init Test">
<msg timestamp="20181030 17:06:57.929" level="FAIL">No keyword with name 'Init Test' found.</msg>
<status status="FAIL" endtime="20181030 17:06:57.929" starttime="20181030 17:06:57.929"></status>
</kw>
<kw type="teardown" name="Record Test Status">
<msg timestamp="20181030 17:06:57.931" level="FAIL">No keyword with name 'Record Test Status' found.</msg>
<status status="FAIL" endtime="20181030 17:06:57.932" starttime="20181030 17:06:57.931">No keyword with name 'Record Test Status' found.</status>
</kw>
<tags>
<tag>CCO</tag>
</tags>
<status status="FAIL" endtime="20181030 17:06:57.932" critical="yes" starttime="20181030 17:06:57.926">Setup failed:
No keyword with name 'Init Test' found.

Also teardown failed:
No keyword with name 'Record Test Status' found.</status>
</test>
<status status="FAIL" endtime="20181030 17:06:57.932" starttime="20181030 17:06:57.912"></status>
</suite>
<status status="FAIL" endtime="20181030 17:06:57.933" starttime="20181030 17:06:57.894"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
<stat fail="1" pass="0">CCO</stat>
</tag>
<suite>
<stat fail="1" id="s1" name="Plc System Test" pass="0">Plc System Test</stat>
<stat fail="1" id="s1-s1" name="Tc.3.3.3" pass="0">Plc System Test.Tc.3.3.3</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20181030 17:06:57.867" level="ERROR">Taking listener 'listener' into use failed: Importing listener 'listener' failed: ImportError: No module named listener
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\windows\SYSTEM32\python27.zip
  C:\Program Files\python2\DLLs
  C:\Program Files\python2\lib
  C:\Program Files\python2\lib\plat-win
  C:\Program Files\python2\lib\lib-tk
  C:\Program Files\python2
  C:\Program Files\python2\lib\site-packages
  C:\Program Files\python2\lib\site-packages\wx-2.8-msw-unicode</msg>
<msg timestamp="20181030 17:06:57.925" level="ERROR">Error in file 'D:\svn\sources\SIWP9006\plc_system_test\tc.3.3.3.robot': Importing test library 'plc_tb_ctrl' failed: ImportError: No module named plc_tb_ctrl
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\windows\SYSTEM32\python27.zip
  C:\Program Files\python2\DLLs
  C:\Program Files\python2\lib
  C:\Program Files\python2\lib\plat-win
  C:\Program Files\python2\lib\lib-tk
  C:\Program Files\python2
  C:\Program Files\python2\lib\site-packages
  C:\Program Files\python2\lib\site-packages\wx-2.8-msw-unicode</msg>
<msg timestamp="20181030 17:06:57.926" level="ERROR">Error in file 'D:\svn\sources\SIWP9006\plc_system_test\tc.3.3.3.robot': Importing test library 'plc_tb_ctrl.PlcSystemTestbench' failed: ImportError: No module named plc_tb_ctrl
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\windows\SYSTEM32\python27.zip
  C:\Program Files\python2\DLLs
  C:\Program Files\python2\lib
  C:\Program Files\python2\lib\plat-win
  C:\Program Files\python2\lib\lib-tk
  C:\Program Files\python2
  C:\Program Files\python2\lib\site-packages
  C:\Program Files\python2\lib\site-packages\wx-2.8-msw-unicode</msg>
</errors>
</robot>
