<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20181122 20:08:46.480" generator="Robot 3.0.2 (Python 2.7.15 on win32)">
<suite source="C:\D\plc_system_test" id="s1" name="Plc System Test">
<suite source="C:\D\plc_system_test\tc.4.robot" id="s1-s1" name="Tc.4">
<test id="s1-s1-t1" name="tc_4.1">
<kw name="run iot test">
<arguments>
<arg>tc_4_1</arg>
</arguments>
<msg timestamp="20181122 20:08:47.381" level="FAIL">No keyword with name 'run iot test' found.</msg>
<status status="FAIL" endtime="20181122 20:08:47.381" starttime="20181122 20:08:47.381"></status>
</kw>
<kw type="teardown" name="Record Test Status" library="plc_tb_ctrl">
<msg timestamp="20181122 20:08:47.391" level="FAIL">NameError: global name 'TB_INSTANCE' is not defined</msg>
<msg timestamp="20181122 20:08:47.391" level="DEBUG">Traceback (most recent call last):
  File "C:\D\plc_system_test\lib\plc_tb_ctrl.py", line 153, in record_test_status
    _trace_printf(tc_msg)
  File "C:\D\plc_system_test\lib\plc_tb_ctrl.py", line 88, in _trace_printf
    _write_log_file(LOG_ID_PRINTF, log_data)
  File "C:\D\plc_system_test\lib\plc_tb_ctrl.py", line 78, in _write_log_file
    if TB_INSTANCE is not None:</msg>
<status status="FAIL" endtime="20181122 20:08:47.391" starttime="20181122 20:08:47.381">NameError: global name 'TB_INSTANCE' is not defined</status>
</kw>
<status status="FAIL" endtime="20181122 20:08:47.391" critical="yes" starttime="20181122 20:08:47.381">No keyword with name 'run iot test' found.

Also teardown failed:
NameError: global name 'TB_INSTANCE' is not defined</status>
</test>
<status status="FAIL" endtime="20181122 20:08:47.391" starttime="20181122 20:08:47.341"></status>
</suite>
<status status="FAIL" endtime="20181122 20:08:47.391" starttime="20181122 20:08:47.327"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Plc System Test" pass="0">Plc System Test</stat>
<stat fail="1" id="s1-s1" name="Tc.4" pass="0">Plc System Test.Tc.4</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20181122 20:08:47.381" level="ERROR">Error in file 'C:\D\plc_system_test\tc.4.robot': Importing test library 'lib/plc_tb_ctrl.PlcSystemTestbench' failed: ImportError: Import by filename is not supported.
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\D\plc_system_test\lib
  C:\Windows\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode</msg>
</errors>
</robot>
