<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20181127 11:25:38.170" generator="Robot 3.0.2 (Python 2.7.15 on win32)">
<suite source="C:\D\plc_system_test" id="s1" name="Plc System Test">
<suite source="C:\D\plc_system_test\tc.4.robot" id="s1-s1" name="Tc.4">
<test id="s1-s1-t1" name="tc_4.1">
<kw type="setup" name="Init Test" library="plc_tb_ctrl">
<msg timestamp="20181127 11:25:38.377" level="INFO">start detail logging</msg>
<status status="PASS" endtime="20181127 11:25:43.377" starttime="20181127 11:25:38.377"></status>
</kw>
<kw name="Run Iot Test" library="plc_tb_ctrl.PlcSystemTestbench">
<arguments>
<arg>tc_4_1</arg>
</arguments>
<msg timestamp="20181127 11:25:43.377" level="INFO">power off all of meters and cco, delay 5s</msg>
<msg timestamp="20181127 11:25:48.393" level="INFO">Open concentrator port</msg>
<msg timestamp="20181127 11:25:48.393" level="INFO">power on all of meters and cco. delay 5s for boot</msg>
<msg timestamp="20181127 11:25:53.395" level="INFO">Close TB port</msg>
<msg timestamp="20181127 11:25:53.614" level="INFO">Open TB port</msg>
<msg timestamp="20181127 11:25:53.614" level="INFO">C:\D\plc_system_test\\</msg>
<msg timestamp="20181127 11:25:53.708" level="INFO">Wait for gdw1376p2 frame. DIR=UL, AFN=3,DT1=2,DT2=1</msg>
<msg timestamp="20181127 11:25:53.708" level="INFO">Received</msg>
<msg timestamp="20181127 11:25:53.708" level="INFO">Wait for gdw1376p2 frame. DIR=UL, AFN=3,DT1=128,DT2=1</msg>
<msg timestamp="20181127 11:25:53.755" level="INFO">Exp afn: 3, Recv: 0 </msg>
<msg timestamp="20181127 11:26:03.709" level="FAIL">10 seconds timeout</msg>
<msg timestamp="20181127 11:26:03.709" level="DEBUG">Traceback (most recent call last):
  File "C:\D\plc_system_test\lib\plc_tb_ctrl.py", line 359, in run_iot_test
    tc.run(self, b)
  File "C:\D\plc_system_test\\tc\tc_iot_4\tc_4_1.py", line 33, in run
    r_band = tc_common.read_cco_band(tb.cct)
  File "C:\D\plc_system_test\lib\tc_common.py", line 1527, in read_cco_band
    afn03h16 = cct.wait_for_gdw1376p2_frame(afn=0x03, dt1=0x80, dt2=1)
  File "C:\D\plc_system_test\lib\concentrator.py", line 189, in wait_for_gdw1376p2_frame
    raise AssertionError(timeout_error)</msg>
<status status="FAIL" endtime="20181127 11:26:03.709" starttime="20181127 11:25:43.377"></status>
</kw>
<kw type="teardown" name="Record Test Status" library="plc_tb_ctrl">
<msg timestamp="20181127 11:26:03.709" level="INFO">begin 5 seconds waiting before exit...</msg>
<msg timestamp="20181127 11:26:09.710" level="INFO">stop detail logging</msg>
<status status="PASS" endtime="20181127 11:26:09.710" starttime="20181127 11:26:03.709"></status>
</kw>
<status status="FAIL" endtime="20181127 11:26:09.710" critical="yes" starttime="20181127 11:25:38.377">10 seconds timeout</status>
</test>
<status status="FAIL" endtime="20181127 11:26:09.710" starttime="20181127 11:25:38.295"></status>
</suite>
<status status="FAIL" endtime="20181127 11:26:09.725" starttime="20181127 11:25:38.264"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Plc System Test" pass="0">Plc System Test</stat>
<stat fail="1" id="s1-s1" name="Tc.4" pass="0">Plc System Test.Tc.4</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
